### ISSUE TITLE
"Visit the curriculum" nav element misaligned on forum

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/forum-theme#112]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/b28d2dc7-8a45-43b0-b5b2-d8579e216dae)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/4b104110-a17d-4334-9f5e-76c276aabcf0)

affected page: https://forum.freecodecamp.org/

**Comment by ahmaxed** [comment]
it should look proper now.
