### ISSUE TITLE
"Visit the Curriculum" nav item is partially hidden

### ISSUE THREAD

**Issue by timagixe** [freeCodeCamp/forum-theme#116]
**Describe the bug**
Nav item is partially hidden behind the screen and is not readable, however it stays clickable.

**To Reproduce**
1. Go to https://forum.freecodecamp.org/
2. Take a look on Visit the Curriculum item in nav bar

**Expected behavior**
Item is fully readable and is not partially hidden

**Screenshots**
![image](https://github.com/freeCodeCamp/forum-theme/assets/60817786/678a8348-2225-435a-a543-ad4df15a531b)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Chromium Engine Version 122.0.6261.94

**Comment by timagixe** [comment]
Seems like the issue was introduced within https://github.com/freeCodeCamp/forum-theme/pull/113

@ahmaxed @ojeytonwilliams FYI

**Comment by timagixe** [comment]
Seems margin-top property with negative value is not required, according to my check. Please refer to the attached video.

https://github.com/freeCodeCamp/forum-theme/assets/60817786/4bc46269-8d17-4745-a89d-7c9b45bc2430


By the way, @ahmaxed what was the issue you tried to fix? The PR https://github.com/freeCodeCamp/forum-theme/pull/113 does not contain enough info about the introduced change and what's it fixing.

**Comment by ahmaxed** [comment]
Thanks for reporting the issue. It seems that the margin-top is behaving differently in different browsers. 
Setting the top: 38px initially and reducing it to 0px for screens with (min-width: 800px) should do the trick.

**Comment by timagixe** [comment]
In what browsers did you observe a different behaviour of margin-top property?

> Setting the top: 38px initially and reducing it to 0px for screens with (min-width: 800px) should do the trick.

I have just removed `margin-top: -19px;` and checked Safari, Chrome, Firefox -> the result was the same in all browsers. Why do we need to set top: 39px; for screen width < 800px; and top: 0px; for screen width >= 800px?

Could you please provide some extra details about the issue the https://github.com/freeCodeCamp/forum-theme/pull/113 fixes?

**Comment by ahmaxed** [comment]
Here is the main issue:
https://github.com/freeCodeCamp/forum-theme/issues/112

I double checked it in chrome, it looks like on incognito (without the extensions) I am not getting the issue.

**Comment by timagixe** [comment]
I have checked in incognito mode in Chrome, and here is how it looks on 1400px width and 798px width right now.

<details><summary>Details</summary>

<img width="1438" alt="Screen Shot 2024-03-08 at 10 30 04 AM" src="https://github.com/freeCodeCamp/forum-theme/assets/60817786/0ff2a1c9-ec74-468a-8ab1-16139f28742d">

<img width="785" alt="Screen Shot 2024-03-08 at 10 30 18 AM" src="https://github.com/freeCodeCamp/forum-theme/assets/60817786/f0629053-869d-4f59-8e70-4dc3010f1cc8">


</details> 

An below you can find out how it looks like when I deleted negative margin - `margin-top: -19px;` The same applies to Chrome, Firefox, Safari as per my checks.

<details><summary>Details</summary>

<img width="1419" alt="Screen Shot 2024-03-08 at 10 32 46 AM" src="https://github.com/freeCodeCamp/forum-theme/assets/60817786/bcd49cab-403b-4f41-8893-523a994f6ce4">

<img width="775" alt="Screen Shot 2024-03-08 at 10 33 00 AM" src="https://github.com/freeCodeCamp/forum-theme/assets/60817786/ff44a8b9-974c-4a7e-8e3a-3ecff8df54cd">


</details> 

It looks better without negative margin.
