### ISSUE TITLE
Navbar wraps incorrectly when using the leaderboard page

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/forum-theme#125]
On leaderboard page:

<img width="1208" alt="image" src="https://github.com/freeCodeCamp/forum-theme/assets/1884376/cdc031a5-418c-44f1-b079-e1ba68fe3f04">

Everywhere else:

<img width="1203" alt="image" src="https://github.com/freeCodeCamp/forum-theme/assets/1884376/6655182e-0c81-4743-b063-bdacc4f29e72">

This issue could be in the https://github.com/freeCodeCamp/forum-users-nav component, which we had forked for some reason.

**Comment by a2937** [comment]
Should we resync the forum users nav?

**Comment by raisedadead** [comment]
So we have switched to using the official plugin now. The issue still remains. For the URLs we have added permalinks.

**Comment by a2937** [comment]
Now that I actually have a Meta Discourse account, I don't see the navbar on what I believe to be the Leaderboard.

**Comment by a2937** [comment]
I know what class is missing on the forums. I don't know how to edit it though. There's supposed to be this element with a class of `navigation-container` that keeps everything on a single line. It needs to contain the `category-breadcrumb` and `nav nav-pills` and `navigation-controls` element though.

**Comment by raisedadead** [comment]
Thanks for investigating, I am hopping @ahmaxed or @huyenltnguyen can help you more.

**Comment by a2937** [comment]
I think I began the process of fixing it already. 

https://github.com/discourse/discourse-users-nav/pull/20/files

**Comment by raisedadead** [comment]
Thanks - you should potentially mention this thread there for context to the maintainers of that project.

**Comment by ahmaxed** [comment]
The proposed solution will resolve the issue. I would need access to that repo to approve, and merge.
