### ISSUE TITLE
forum theme update broken

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/forum-theme#92]
Recently, an update to the Discourse UI has broken our theme:
![image](https://user-images.githubusercontent.com/51722130/221220906-1784606d-e8d6-46a8-a048-623b8801504a.png)

The notifications are the only things I have noticed being broken, but who knows 🤷‍♂️ 

The main thing to figure out is what the original (intended) background colour should be.

**Comment by ahmadabdolsaheb** [comment]
It seems like the hover states on the nav items are also affected.
<img width="354" alt="Screen Shot 2023-02-25 at 8 50 20 AM" src="https://user-images.githubusercontent.com/4591597/221340967-47f270bd-a798-4732-8484-675da879db81.png">

**Comment by ShaunSHamilton** [comment]
Linked PR merged
